apiVersion: v1
kind: Secret
metadata:
  name: gfg-secret
type: Opaque # this is the default type
data: # key value pairs that we want to save in secret.
  mongo-root-username: c2h1YmhhbQ==
  mongo-root-password: Y3JhenlQYXNzd29yZA==
